In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [2]:
alpha = np.deg2rad(10.0)
beta = np.deg2rad(45.0)
p0 = np.array([1, 0, 1])
d0 = np.array([np.cos(alpha), 0.0, np.sin(alpha)])

p1 = np.array([-0.4, 0, 0])
d1 = np.array([np.cos(beta), 0.0, np.sin(beta)])

In [3]:
AT = np.vstack((d0, -d1))
A = AT.T

b = (p1 - p0).reshape(-1, 1)

TypeError: bad operand type for unary -: 'tuple'

In [21]:
C = np.matmul(AT, A)
d = np.matmul(AT, b)

In [22]:
C

array([[ 1.        , -0.81915204],
       [-0.81915204,  1.        ]])

In [23]:
d

array([[-1.55237903],
       [ 1.69705627]])

In [24]:
t, s = np.linalg.solve(C, d)

In [25]:
t

array([-0.49312122])

In [26]:
s

array([1.29311502])

In [27]:
p0 + t*d0

array([0.5143704, 0.       , 0.9143704])

In [28]:
p1 + s*d1

array([0.5143704, 0.       , 0.9143704])